

FROM golang:alpine

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod . go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Build the application
RUN go build -o web_server_application .

# Move to /dist directory as the place for resulting binary folder
WORKDIR /dist

# Copy binary from build to main folder
RUN cp /build/web_server_application .

# Export necessary port
EXPOSE 80

# Command to run when starting the container
CMD ["/dist/web_server_application"]